AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-authorizer

  Sample SAM Template for lambda-authorizer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - x86_64
    MemorySize: 512
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        POOL_ID: us-east-1_LrlW4uZUb
        MY_COGNITO_POOL_ID: '{{resolve:secretsmanager:/cognito/appClientId:SecretString}}'
        MY_COGNITO_USER_POOL_ID: '{{resolve:secretsmanager:/cognito/appClientId:SecretString}}'
#        MY_COGNITO_CLIENT_APP_SECRET: '{{resolve:secretsmanager:/cognito/appClientSecret:SecretString}}'
        MY_COGNITO_ID: '{{resolve:secretsmanager:/cognito/id:SecretString}}'
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/

Resources:
  Apigateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: open-api.yaml
  GetUserByUsernameHandlerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaAuthorizer
      Handler: br.com.likwi.aws.GetUserByUsernameHandler::handleRequest
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'cognito-idp:AdminGetUser'
              Resource: "arn:aws:cognito-idp:us-east-1:012821307542:userpool/us-east-1_LrlW4uZUb"
      Events:
        GetUserByUsername:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /users/{user_name}
            Method: get
            RestApiId:
              Ref: Apigateway
  LambdaAuthorizerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaAuthorizer
      Handler: br.com.likwi.aws.authorizer.LambdaAuthorizer::handleRequest
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GetUserByUsernameApi:
    Description: "API Gateway endpoint URL for Prod stage for Get User by Username function"
    Value: !Sub "https://${Apigateway}.execute-api.${AWS::Region}.amazonaws.com/dev/users"
  GetUserByUsernameHandlerFunction:
    Description: "Get User by Username Function ARN"
    Value: !GetAtt GetUserByUsernameHandlerFunction.Arn
  GetUserByUsernameHandlerFunctionIamRole:
    Description: "Implicit IAM Role created for Get User by Username function"
    Value: !GetAtt GetUserByUsernameHandlerFunctionRole.Arn
